### ISSUE TITLE
template settings not being saved using Configuration Manager gui

### ISSUE THREAD

**Issue by deefster** [foundata/dokuwiki-template-monobook#6] opened 2014-02-17 17:26 UTC
I confirmed that setting basic configuration settings, such as template, date format, etc works.
Setting monobook template settings reports successful, but they don't actually update.

I noticed fields are missing from local.php, but they show up in local.php.bak.
Some examples:
$conf['tpl']['monobook']['monobook_discuss'] 
$conf['tpl']['monobook']['monobook_sitenotice']
If I copy local.php.bak back to local.php on the command line and edit them with vi, the settings take.
I verified ownership (apache:apache) on the entire dokuwiki directory structure and subdirectories.

Here is the contents of VERSION under lib/tpl/monobook
2013-11-17

Here is the data returned by do=check, ie  id=start&do=admin&page=config&do=check

DokuWiki version: Release 2013-12-08 "Binky"
PHP version 5.5.9-pl0-gentoo
More than 32MB RAM (134217728 bytes) available.
Changelog is writable
Old changelog exists
conf directory is writable
mb_string extension is available and will be used
Your locale C seems not to be a UTF-8 locale, you should fix this if you encounter problems.
Debugging support is disabled
**You are currently logged in as ### (Full Name)**  username scrubbed
You are part of the groups admin, user
Your current permission for this page is 255
The current page is writable by the webserver
The current page is writable by you
The search index seems to be working
You are here: start

**Comment by andreashaerter** [comment] 2014-02-17 17:34
Thanks for reporting this. However, this bug is fixed in the current template release (2014-02-09), cf. issues #5. So you just have to upgrade the template (= just uncompress the new release and copy it over your current /lib/tpl/monobook in most cases; see the [description](https://www.dokuwiki.org/template:monobook#i_am_using_a_version_newer_or_equal_2010-01-12_by_andreas_haerter_-_what_to_do_to) for details).

It was caused by a config parser change between Binky RC2 and Binky final (see [mailinglist posting](http://www.freelists.org/post/dokuwiki/SemiUrgent-broken-template-config-in-final-Binky,1) for more information)

**Closed as completed by andreashaerter** 2014-02-17 17:34 UTC
